trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'VS2017-Win2016'

steps:
    
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    projects: '**/*.Tests/*.csproj'
    command: 'test'
